server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoguangdong999/store-parent
          search-paths:
            - config
      label: master
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8901/eureka/


