server:
  port: 8701

spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka
zuul:
  routes:
    account:
      path: /account/**
      serviceId: account
    good:
      path: /good/**
      serviceId: good
    chat:
      path: /chat/**
      serviceId: chat
    order:
      path: /order/**
      serviceId: order
  ignored-services: card
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
